DROP TABLE IF EXISTS Location CASCADE;
DROP TABLE IF EXISTS Room CASCADE;
DROP TABLE IF EXISTS Guest CASCADE;
DROP TABLE IF EXISTS Booking CASCADE;


CREATE TYPE STATUS AS ENUM ('Reserved', 'Paid', 'Canceled');

CREATE Table Guest (
	GuestID SERIAL PRIMARY KEY, 
	GuestName TEXT NOT NULL,
	PhoneNumber BIGINT NOT NULL UNIQUE,
	Age SMALLINT CHECK (Age >= 18),
	LoyaltyMember BOOLEAN NOT NULL DEFAULT FALSE
);

CREATE TABLE Location (
	BuildingID SERIAL PRIMARY KEY,
	Amenities TEXT,
	Address TEXT NOT NULL,
	PhoneNumber VARCHAR(20) NOT NULL,
	LocationName TEXT NOT NULL
);

CREATE Table Room (
	RoomID SERIAL PRIMARY KEY,
	Price SMALLINT NOT NULL check(Price > 0),
	BedCount SMALLINT NOT NULL check(BedCount > 0),
	RoomType TEXT NOT NULL,
	RoomNumber TEXT NOT NULL,
	PetFriendly BOOL NOT NULL,
	Accessible BOOL NOT NULL,
	SmokeFree BOOL NOT NULL,
    BuildingID INT references Location(BuildingID) NOT NULL
);

CREATE TABLE Booking (
	BookingID SERIAL PRIMARY KEY,
	RoomID INT NOT NULL REFERENCES Room (RoomID),
	StartDate DATE NOT NULL CHECK (StartDate >= CURRENT_DATE), 
	EndDate DATE NOT NULL CHECK (EndDate >= StartDate),
	GuestID INT NOT NULL REFERENCES Guest (GuestID),
	CheckedIn BOOLEAN NOT NULL,
	CheckedOut BOOLEAN NOT NULL,
	Ready BOOLEAN NOT NULL,
	Housekeeper INT REFERENCES Housekeeper(StaffID)
	Status STATUS NOT NULL DEFAULT 'Reserved'
);


CREATE TABLE Staff (
    StaffID SERIAL PRIMARY KEY,
    Name VARCHAR(100) NOT NULL,
    PhoneNumber VARCHAR(15) NOT NULL,
    BuildingID INTEGER NOT NULL REFERENCES Location(buildingid)
);

CREATE TABLE Housekeeper (
    StaffID INT PRIMARY KEY REFERENCES Staff(StaffID) ON DELETE CASCADE,
	MonAvail BOOLEAN DEFAULT FALSE,
	TuesAvail BOOLEAN DEFAULT FALSE,
	WedAvail BOOLEAN DEFAULT FALSE,
	ThursdAvail BOOLEAN DEFAULT FALSE,
	FriAvail BOOLEAN DEFAULT FALSE,
	SatAvail BOOLEAN DEFAULT FALSE,
	SunAvail BOOLEAN DEFAULT FALSE
);

CREATE TABLE FrontWorker (
    StaffID INT PRIMARY KEY REFERENCES Staff(staffid) ON DELETE CASCADE,
    username VARCHAR(50) UNIQUE NOT NULL,
    password VARCHAR(255) NOT NULL
);



